// <auto-generated />
namespace MyElearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_add_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_add_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "202411261414162_mig_add_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
