// <auto-generated />
namespace MyElearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_update_aboutIcon_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_update_aboutIcon_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202412050821592_mig_update_aboutIcon_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
